# Page settings

baseurl = "https://rob.lolbert.com/"
languageCode = "en-us"
title = "Robert J. Lambert III"
theme = "dev-resume"
googleAnalytics = "UA-13189879-6"
publishDir = "docs"

# Do not build files for websites. Need them? Set to false
disableRSS = false
disableSitemap = false
disable404 = false

[params]

# Meta
    description = "Resume of Robert J. Lambert III"
    author = "Robert J. Lambert III"

# Theme styles

    # The original template comes with 6 colour schemes. You may choose styles below.
    # "styles.css", "styles-2.css", "styles-3.css", "styles-4.css", "styles-5.css", "styles-6.css"
    # are available. Also the source LESS files are included so
    # it’s quick and easy to change the styling and colour scheme.

    styles = "styles.css"

# Sidebar sections

    # Profile section
    [params.profile]
        name = "Robert J. Lambert III"
        tagline = "Experienced Site Reliability Engineer"
        avatar = "it-me.png"

    # Contact section
    [params.contact]
        enable = true

        [[params.contact.list]]
        class = "email"
        icon = "fa-envelope"
        url = "mailto: rlambert85@gmail.com"
        title = "rlambert85@gmail.com"

        [[params.contact.list]]
        class = "website"
        icon = "fa-globe"
        url = "//rob.lolbert.com"
        title = "rob.lolbert.com"

        [[params.contact.list]]
        class = "linkedin"
        icon = "fa-linkedin"
        url = "//linkedin.com/in/rlambert85"
        title = "in/rlambert85"

        [[params.contact.list]]
        class = "github"
        icon = "fa-github"
        url = "//github.com/esoterick"
        title = "github.com/esoterick"

    # Education section
    [params.education]
        enable = true
        title = "Education"

        [[params.education.list]]
        degree = "A.S. Computer Information Systems"
        college = "Hudson Valley Community College, Troy, NY"
        dates = ""

    # Education section
    [params.certs]
        [[params.certs.list]]
        cert = "[Machine Learning](https://www.coursera.org/account/accomplishments/certificate/WEHTQAGU37TK)"
        location = "Stanford Online"

    # Languages section
    [params.language]
        enable = false
        title = "Languages"

        [[params.language.list]]
        language = "English"
        level = "Native"

        [[params.language.list]]
        language = "Python"
        level = "Professional"

        [[params.language.list]]
        language = "Go"
        level = "Professional"

    # Interests section
    [params.interests]
        enable = true
        title = "Interests"

        [[params.interests.list]]
        interest = "My Family"

        [[params.interests.list]]
        interest = "My Dogs"

        [[params.interests.list]]
        interest = "Graphics and Game Programming"

        [[params.interests.list]]
        interest = "3D Printing"

        [[params.interests.list]]
        interest = "Music Production"

        [[params.interests.list]]
        interest = "Home Automation"

        [[params.interests.list]]
        interest = "Machine Learning"

# Main body sections

    # You may use markdown in summary, details and intro fields. But don't overdose, it's resume!:)

    # Summary section
    [params.summary]
        enable = true
        icon = "fa-user"
        title = "Career Profile"
        summary = """
I wrote my first computer program over 20 years ago on a Commodore 64 in BASIC, which inspired me to gain my college accreditation in Computer Information Systems, and pursue a professional career in this field. Now, with over 13 years of professional, real-world experience, I find myself constantly in search of knowledge and new skill sets. Most recently, I've taken pride in working on multiple new teams as the need arrises to assist in improving the stability and reliability of systems at [DigitalOcean](https://www.digitalocean.com/).
"""

    # Experiences section
    [params.experiences]
        enable = true
        icon = "fa-briefcase"
        title = "Experiences"

        [[params.jobs.list]]
        position = "Senior Infrastructure Engineer"
        dates = "2020 - Present"
        company = "DigitalOcean - Remote"
        details = """
Currently working as Senior Engineer under the Data Program group at [DigitalOcean](https://www.digitalocean.com/), which entails a large group of internal product ownership. My responsibilities include, but are not limited to, maintaining our legacy Mesos environment and the majority of the applications running in that environment. Currently focusing on migrating the platform for a hardware refresh.

- Monitor, troubleshoot, maintain, extend and improve the legacy Mesos stack
- Deploy changes to thousands of containers running on this cluster using Ansible, and Chef
- Built custom automated reports against this platform using Bash, Ansible and Pythnon
- Managed deployment of configs via [Ansible](https://www.ansible.com/) the current stack runs multiple high priority internal workloads
- Currently maintaining the production Hadoop stack at [DigitalOcean](https://www.digitalocean.com/) 
- Improvment in monitoring with custom Hadoop/HDFS exporters
- Provide support for one of our legacy Kafka platforms as well as refresh monitoring while developers work to migrate to a newer Kafka platform
- Create design documents, architecture designs, and other high level design documents to provide information to management to help make critical design decissions for our environments
"""

        [[params.jobs.list]]
        position = "Senior Infrastructure Engineer"
        dates = "2019 - 2020"
        company = "DigitalOcean - Remote"
        details = """
Was brought in on the Infrastructre Core team to help troubleshoot and fix the aging Chef Platform. Worked on root cause analysis for multiple chef build pipeline issues affecting tens of thousands of hosts in production. Worked with numerous interal teams to support them in building and scaling their Chef cookbooks using Chef best practices.

- Determine RCA on issues reguarding Chef builds and deployments
- Built Chef Cookbooks for the deployment of [Chef Automate](https://www.chef.io/products/automate) HA cluster which included ElasticSearch, PostgreSQL and Nginx components
- Built internal service utilizing Okta and Vault allowing new [DigitalOcean](https://www.digitalocean.com/) Developers to self service deploy their own chef user
- Built Chef module using [Optimizely](https://www.optimizely.com/) for scheduling and tracking Chef deployment changes across our entire fleet of machines
- Built automation around tasks that wasted engineer time and that we're prone to error
- Built reusable [Terraform](https://www.terraform.io/) modules for internal users to deploy private virtual machines to mange internal tooling, complete with 
- Built generic workflow for [Atlantis](https://www.runatlantis.io/) allowing internal users to move to a more secure (using [Vault](https://www.vaultproject.io/)) automated [Terraform](https://www.terraform.io/) provisioning experience
"""

        [[params.jobs.list]]
        position = "Senior Site Reliability Engineer"
        dates = "2018 - 2019"
        company = "LinkedIn - Sunnyvale, CA"
        details = """
- Represented LinkedIn's [Espresso](https://engineering.linkedin.com/teams/data/projects/espresso) Team in cross-organizational stand-ups to provide both executions of complex tasks, and act as a single point of contact for our team
- Maintained multiple internal products which included upgrading multiple legacy codebases to Python3 and Go
- Designed and implemented global availability, cross data center consistency, and cross data center latency metrics and SLAs for all [Espresso](https://engineering.linkedin.com/teams/data/projects/espresso) clusters
- Trained and onboarded new [Espresso](https://engineering.linkedin.com/teams/data/projects/espresso) SREs, which enabled them to contribute to our ecosystem in under 3 months

**Above and beyond**

- Completed the Machine Learning course offered through Stanford Online: [Verification](https://www.coursera.org/account/accomplishments/certificate/WEHTQAGU37TK)
- Member of the interview and hiring committees of SREs, Senior SREs, and Managers
- Organized, hosted, and presented at the first [Espresso](https://engineering.linkedin.com/teams/data/projects/espresso) SRE Hackday
- Taught ongoing SRE Bootcamp series, as part of the new hire onboarding process
"""

        [[params.jobs.list]]
        position = "Site Reliability Engineer"
        dates = "2017 - 2018"
        company = "LinkedIn - Sunnyvale, CA"
        details = """
- Collaborated across teams to build the [Espresso](https://engineering.linkedin.com/teams/data/projects/espresso) Data layer for a new logical data center
- Provided documentation improvements for [Espresso](https://engineering.linkedin.com/teams/data/projects/espresso) cluster creation, consuming tribal knowledge from multiple sources into useful runbooks
- Designed, built and maintained 120+ node ELK cluster handling all of [Espresso](https://engineering.linkedin.com/teams/data/projects/espresso)'s logging data across 4 data centers
- Built service overview dashboards for each [Espresso](https://engineering.linkedin.com/teams/data/projects/espresso) owned service reducing both MTTR and MTTD
- Acted as lead on 80% of all [Espresso](https://engineering.linkedin.com/teams/data/projects/espresso) [GDPR](https://gdpr-info.eu/) related horizontal initiatives, overseeing both the design and resolution
- Oversaw the data migrations of [Espresso](https://engineering.linkedin.com/teams/data/projects/espresso) clusters, which involved coordinating between teams both onsite and offshore
"""

        [[params.jobs.list]]
        position = "Site Reliability Engineer"
        dates = "2016 - 2017"
        company = "CDPHP - Albany, NY"
        details = """
- Maintained a balance of operational and development work to ensure critical business services were responsive
- Provided engineering and development teams with custom tooling built off known frameworks
- Designed [Ansible](https://www.ansible.com/) and [CFengine](https://cfengine.com/) code to automate operational and system level tasks to improve performance, provide higher reliability and scale when needed
- Designed and implemented ELK log monitoring solution, with [FileBeats](https://www.elastic.co/products/beats/filebeat), [NXLog](https://nxlog.co/products/nxlog-community-edition), [Kafka](https://kafka.apache.org/), [Logstash](https://www.elastic.co/products/logstash), [ElasticSearch](https://www.elastic.co/products/elasticsearch), [Kibana](https://www.elastic.co/products/kibana)
"""

        [[params.jobs.list]]
        position = "Systems Engineer II"
        dates = "2015 - 2016"
        company = "CDPHP - Albany, NY"
        details = """
- Designed and implemented custom integration systems between our enterprise monitoring solutions, CMDB, operator runbook, ITSM tool, and [CFEngine](https://cfengine.com/) our configuration management platform
- Integrated APM solution [AppDynamics](https://www.appdynamics.com/) with existing [Opsview](https://www.opsview.com/) monitoring environment
- Focused on the design and implementation of the [Mulesoft Enterprise Service Bus](https://www.mulesoft.com/), which had both on-premise and [AWS](https://aws.amazon.com/) components
"""

        [[params.jobs.list]]
        position = "Systems Engineer I"
        dates = "2014 - 2015"
        company = "CDPHP - Albany, NY"
        details = """
- Built CFEngine solution backed with Ansible ad-hoc tasks for constructing simple reports
- Replaced [Tivoli Enterprise Portal](https://www.ibm.com/support/knowledgecenter/en/SS4EKN_7.2.0/com.ibm.itm.doc_6.3/install/tep_overview.htm) with Nagios fork [Opsview](https://opsview.com/)
- Handled day to day operational work such as: diagnosing web performance issues, code misconfigurations, as well as other internal infrastructure problems
"""

        [[params.jobs.list]]
        position = "DevOps Contractor"
        dates = "2015"
        company = "Edhesive - Remote"
        details = """
- Collaborated remotely with engineers across the country to gather detailed project requirements
- Built automated backup and recovery solution for Rails and Flask based application, in [AWS](https://aws.amazon.com/) and [GAE](https://cloud.google.com/appengine/)
- Wrote detailed design documents and runbook information
"""

        [[params.jobs.list]]
        position = "Linux Systems Administrator"
        dates = "2010 - 2014"
        company = "Xerox - Albany, NY"
        details = """
- Installed and maintained servers in multi-site tier 3 and 4 data centers located internationally
- Traveled overseas to work directly with clients on site to provide support for the custom virtualized appliance
- Designed custom software solutions to reduce costs of operational expenses by utilizing open source solutions rather than purchasing an enterprise solution
- Engineered IT solutions to accommodate changing environments and project requirements from clients while actively working with other departments to resolve any issues in a timely manner
"""

        [[params.jobs.list]]
        position = "NOC Operator"
        dates = "2007 - 2010"
        company = "Xerox - Albany, NY"
        details = """
- Provided 24-hour support for Clients and Client Managers for all of the [XLS](https://www.conduent.com/legal-business-services/) products and infrastructure
- Monitored logs and custom alerting software to initiate the resolution of any potential or incipient issues
- Programmed enhancements for internal monitoring software such as upgrading the web application to use AJAX over the old static layout
"""

    # Projects section
    [params.projects]
        enable = true
        icon = "fa-archive"
        title = "Projects"
        intro = """
**Open Source** Daily support of the following open source products
"""

        [[params.projects.list]]
        title = "Espresso"
        url = "https://engineering.linkedin.com/espresso/introducing-espresso-linkedins-hot-new-distributed-document-store"
        tagline = "LinkedIn's online, distributed, fault-tolerant, NoSQL database that currently powers over 30 LinkedIn applications including member profile, InMail (LinkedIn's member-to-member messaging system), portions of the homepage, mobile applications, and more."

        [[params.projects.list]]
        title = "Kafka"
        url = "https://kafka.apache.org/"
        tagline = "Distributed streaming platform. Used across all engineering to stream data reliably. Used by Espresso to handle cross data center replication."

        [[params.projects.list]]
        title = "Helix"
        url = "https://git-wip-us.apache.org/repos/asf?p=helix.git;a=summary"
        tagline = "Cluster management framework for partitioned and replicated distributed resources. Helix powers not only [Espresso](https://engineering.linkedin.com/teams/data/projects/espresso) but numerous other technologies I've worked on at LinkedIn that require Master/Slave or Active/Passive architectures."

    # Skills section
    [params.skills]
        enable = true
        icon = "fa-rocket"
        title = "Skills & Proficiency"

        [[params.skills.list]]
        skill = "Linux"

        [[params.skills.list]]
        skill = "Bash"

        [[params.skills.list]]
        skill = "Python"

        [[params.skills.list]]
        skill = "Rust"

        [[params.skills.list]]
        skill = "C/C++"

        [[params.skills.list]]
        skill = "Chef"

        [[params.skills.list]]
        skill = "Ansible"

        [[params.skills.list]]
        skill = "Terraform"

        [[params.skills.list]]
        skill = "Vault"

        [[params.skills.list]]
        skill = "Consul"

        [[params.skills.list]]
        skill = "Docker"

        [[params.skills.list]]
        skill = "Kubernetes"

        [[params.skills.list]]
        skill = "Monitoring and Logging"

        [[params.skills.list]]
        skill = "Distributed Systems"

        [[params.skills.list]]
        skill = "Performance Tuning"

    # Footer section

    # The original template is released under the Creative Commons Attribution 3.0 License.
    # Please keep the original attribution link when using for your own project.
    # If you'd like to use the template without the attribution,
    # you can check out other license options via template author's website: themes.3rdwavemedia.com
    #
    # As for Hugo port you may rewrite the "Ported for..." line with setting your name below.

    [params.footer]
        copyright = "Robert J. Lambert III"
